[project]
name = "dqmj1_info"
version = "0.0.1"

[project.scripts]
dqmj1_extract_files = "dqmj1_info:extract_files.main_without_args"
dqmj1_compile_evt = "dqmj1_info:compile_evt.main_without_args"

[tool.setuptools]
packages = ["dqmj1_info"]