# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout LFS objects
      run: git lfs pull

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt install libgtk-3-dev
        python -m pip install --upgrade pip
        pip install mypy black pytest ruff pyinstaller
        pip install pandas-stubs types-Pillow
    - name: Lint with mypy
      run: |
        mypy .
    - name: Lint with ruff
      run: |
        ruff check .
    - name: Lint with black
      run: |
        black --check .
    - name: Install package
      run: |
        pip install .
    - name: Run regression tests
      run: |
        make regression_test
    - name: Create exectuable
      run: |
        make compile_executables
    - name: Archive executable
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: dist/extract_files_gui/*